# fly.toml app configuration file generated for locust-foodformer on 2023-10-06T02:33:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "locust-foodformer"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8089
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
